services:
    redis:
        image: redis
        container_name: cache
        expose:
            - 6379
        ports:
            - "6379:6379"
    tilda:
        image: jizacal/tilda:latest
        container_name: mock
        volumes:
            - ./data:/data
        expose: 
            - 5111
            - 80
        ports:
            - "5111:5111"
            